export const DC_ZONES = [
  {
    id: "Zone-01",
    name: "Downtown",
    lat: 38.8951,
    lng: -77.0364,
    baseFlow: 110,
    basePressure: 58,
    priority: "high",
    dma: "DMA-Central",
    note: "High priority — hospitals and federal buildings",
  },
  {
    id: "Zone-02",
    name: "Georgetown",
    lat: 38.9096,
    lng: -77.0654,
    baseFlow: 98,
    basePressure: 60,
    priority: "standard",
    dma: "DMA-NW-1",
    note: "Standard residential pressure zone",
  },
  {
    id: "Zone-03",
    name: "Capitol Hill",
    lat: 38.8899,
    lng: -77.0031,
    baseFlow: 105,
    basePressure: 57,
    priority: "high",
    dma: "DMA-Capitol",
    note: "High priority — Capitol complex vicinity",
  },
  {
    id: "Zone-04",
    name: "Adams Morgan",
    lat: 38.9214,
    lng: -77.0422,
    baseFlow: 92,
    basePressure: 61,
    priority: "standard",
    dma: "DMA-NW-2",
    note: "Mixed residential and commercial mains",
  },
  {
    id: "Zone-05",
    name: "Anacostia",
    lat: 38.8653,
    lng: -76.995,
    baseFlow: 88,
    basePressure: 55,
    priority: "standard",
    dma: "DMA-SE-1",
    note: "Older pipe segment — higher inspection rate",
  },
  {
    id: "Zone-06",
    name: "Cleveland Park",
    lat: 38.936,
    lng: -77.058,
    baseFlow: 90,
    basePressure: 62,
    priority: "standard",
    dma: "DMA-NW-3",
    note: "Standard residential pressure zone",
  },
  {
    id: "Zone-07",
    name: "Navy Yard",
    lat: 38.8765,
    lng: -77.0056,
    baseFlow: 115,
    basePressure: 56,
    priority: "high",
    dma: "DMA-SW-Industrial",
    note: "High priority — industrial and stadium events",
  },
  {
    id: "Zone-08",
    name: "Tenleytown",
    lat: 38.948,
    lng: -77.079,
    baseFlow: 86,
    basePressure: 63,
    priority: "standard",
    dma: "DMA-NW-4",
    note: "Elevated terrain — variable pressure zone",
  },
];
